---
- name : "play 1: testing RESTCONF"
  hosts: routers
  connection: ansible.netcommon.httpapi
  gather_facts: false
  vars:
    cust_vrf_list: []
  tasks: 

    - name: "Grab all VRFs from device"
      uri:
        url: "https://{{ ansible_host }}/restconf/data/Cisco-IOS-XE-native:native/Cisco-IOS-XE-native:vrf"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        method: GET
        return_content: true
        headers:
          Accept: "application/yang-data+json"
        validate_certs: false
      register: result

    - name: "Refine variable"
      set_fact:
        vrf_data: "{{ result['json']['Cisco-IOS-XE-native:vrf']['definition'] }}"


    - name: "Loop through VRFs"
      set_fact:
        cust_vrf_list: "{{ cust_vrf_list + [item.name] }}"
      loop: "{{ vrf_data }}"
      when: item.rd is defined

    - name: "Print customer VRFs"
      ansible.builtin.debug:
        var: cust_vrf_list


    - name: "Grab all interfaces from device"
      uri:
        url: "https://{{ ansible_host }}/restconf/data/Cisco-IOS-XE-vrf-oper:vrf-oper-data"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        method: GET
        return_content: true
        headers:
          Accept: "application/yang-data+json"
        validate_certs: false
      register: result

    - name: "Refine variable"
      set_fact:
        interface_data: "{{ result['json']['Cisco-IOS-XE-vrf-oper:vrf-oper-data']['vrf-entry'] }}"

    - name: "Print Result"
      debug:
        var: "{{ item }}"
      loop: "{{ interface_data }}"

    - name: "The above task prints the whole result, now we're going to try to only capture the interfaces we need"
      debug:
        var: "{{ item }}"
      loop: "{{ interface_data }}"

    - name: "send interface_data to disk"
      ansible.builtin.copy:
        content: "{{ interface_data }}"
        dest: "/home/nromeo/dump/int_data.json"
      delegate_to: localhost 
    
    - name: "Send cust_vrf_list to disk"
      ansible.builtin.copy:
        content: "{{ cust_vrf_list }}"
        dest: "/home/nromeo/dump/cust_data.json"
      delegate_to: localhost

    - name: Print interfaces for specified VRFs
      debug:
        msg: "{{ item['interface'] }}"
      loop: "{{ interface_data }}"
      when: item['vrf-name'] in cust_vrf_list
      



